[build]
  publish = "public"
  command = "hugo --minify --ignoreCache --forceSyncStatic"

[context.production.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
